name: Docker Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Create dummy config files for the Docker build to succeed
      - name: Create mock config files
        run: |
          mkdir -p spotify_advance/apis
          echo "spotify:
            client_id: mock_client_id
            client_secret: mock_client_secret
            redirect_uri: http://localhost:3000

          mongodb:
            uri: mongodb://localhost:27017/" > spotify_advance/apis/conf.yaml

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: spotify-advance:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
